<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
    window.$zopim || (function (d, s) {
        var z = $zopim = function (c) {
            z._.push(c)
        }, $ = z.s =
            d.createElement(s), e = d.getElementsByTagName(s)[0];
        z.set = function (o) {
            z.set.
                _.push(o)
        };
        z._ = [];
        z.set._ = [];
        $.async = !0;
        $.setAttribute("charset", "utf-8");
        $.src = "//v2.zopim.com/?3KpcIYLYgWN1Qr24yiOsC5Uw47yrR8Jn";
        z.t = +new Date;
        $.type = "text/javascript";
        e.parentNode.insertBefore($, e)
    })(document, "script");
</script>
<!--End of Zopim Live Chat Script-->

<script>
    $zopim(function() {
        // Força que a janela permaneça aberta o tempo inteiro.
        $zopim.livechat.window.show();
        //$zopim.livechat.endChat();
        //$zopim.livechat.appendNotes('Teste');

        $zopim.livechat.setName('<?= $this->data['empresa'] ?>');
        $zopim.livechat.addTags('<?= $this->data['modulo'] ?>','<?= $this->data['nomeUsuarioA2'] ?>','Cliente 5 estrelas');

    });
</script>

<script type="text/javascript">

    $zopim(function() {
        $zopim.livechat.window.setOffsetHorizontal(0);
        $zopim.livechat.prechatForm.setGreetings('Please introduce yourself.');
    });
    window.onload = setTimeout(function(){
        $("iframe").contents().find(".logged_in_actions.jx_ui_Widget").remove();
        $("iframe").contents().find(".meshim_widget_widgets_Branding.branding").remove();
    }, 1000);

    // encerra chat
    window.onload = setTimeout(function(){
        $zopim(function() {
            $zopim.livechat.endChat();
            // limpa toda a conversa
            //$zopim.livechat.clearAll();
            //alert($zopim.livechat.isChatting())
        });
    }, 10000);
</script>


<?php
echo $this->data['empresa'];
echo "<br />";
echo $this->data['nomeUsuarioA2'];
echo "<br />";
echo $this->data['nomeUsuarioDigitado'];
echo "<br />";
echo $this->data['telefone'];
echo "<br />";
echo $this->data['modulo'];
?>